name: Build Binaries

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Build Binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then
            EXT=".exe"
          fi
          
          # Build target binary
          go build -v -o dist/trmg-${{ matrix.goos }}-${{ matrix.goarch }}$EXT

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trmg-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/trmg-${{ matrix.goos }}-${{ matrix.goarch }}*
